name: Oracle VPS Sniper

on:
  schedule:
    - cron: '*/20 * * * *' # Tenta pescar a vaga a cada 20 minutos
  workflow_dispatch: # Permite que você aperte um botão para rodar na hora

jobs:
  pescar-vaga:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v3

    - name: Preparar o PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Instalar dependências
      run: composer install --no-dev

    - name: Montar a configuração
      run: |
        echo "${{ secrets.OCI_PRIVATE_KEY }}" > oracle.pem
        echo "OCI_USER_ID=${{ secrets.OCI_USER_ID }}" >> .env
        echo "OCI_TENANCY_ID=${{ secrets.OCI_TENANCY_ID }}" >> .env
        echo "OCI_KEY_FINGERPRINT=${{ secrets.OCI_KEY_FINGERPRINT }}" >> .env
        echo "OCI_REGION=${{ secrets.OCI_REGION }}" >> .env
        echo "OCI_SUBNET_ID=${{ secrets.OCI_SUBNET_ID }}" >> .env
        echo "OCI_IMAGE_ID=${{ secrets.OCI_IMAGE_ID }}" >> .env
        echo "OCI_OCPUS=4" >> .env
        echo "OCI_MEMORY_IN_GBS=24" >> .env
        echo "OCI_AVAILABILITY_DOMAIN=${{ secrets.OCI_AVAILABILITY_DOMAIN }}" >> .env
        echo "OCI_SHAPE=VM.Standard.A1.Flex" >> .env
        echo "OCI_PRIVATE_KEY_FILENAME=oracle.pem" >> .env
        echo "OCI_SSH_PUBLIC_KEY=\"${{ secrets.OCI_SSH_PUBLIC_KEY }}\"" >> .env

    - name: Tentar criar a máquina na Oracle
      run: php index.php
